const menu = [
    // ---------------------------- Korea Foods ----------------------------
    {
        id: 1,
        title: "Tteokbokki", 
        category: "Korea",
        price: 8000,
        currency: "₩",
        img: "https://raw.githubusercontent.com/Overated/Asian-Kitchen/main/img/Korea/1-Tteokbokki.jpg",
        desc: "Spicy rice cakes, serving with fish cake.",
    },
    {
        id: 2,
        title: "Bibimbap", 
        category: "Korea",
        price: 15000,
        currency: "₩",
        img: "https://raw.githubusercontent.com/Overated/Asian-Kitchen/main/img/Korea/2-Bibimbap.webp",
        desc: "Boiling vegetables, serving with special hot sauce.",
    },
    {
        id: 3,
        title: "Jajangmyeon", 
        category: "Korea",
        price: 3800,
        currency: "₩",
        img: "https://raw.githubusercontent.com/Overated/Asian-Kitchen/main/img/Korea/3-Jajangmyeon.webp",
        desc: "Black bean sauce noodle, serving with green onion.",
    },
    {
        id: 4,
        title: "Kimchi", 
        category: "Korea",
        price: 11200,
        currency: "₩",
        img: "https://raw.githubusercontent.com/Overated/Asian-Kitchen/main/img/Korea/4-Kimchi.webp",
        desc: "A spicy and sour dish made up of fermented vegetables.",
    },
    {
        id: 5,
        title: "Samgyetang", 
        category: "Korea",
        price: 15000,
        currency: "₩",
        img: "https://raw.githubusercontent.com/Overated/Asian-Kitchen/main/img/Korea/5-Samgyetang.webp",
        desc: "A common dish particularly during the summer, samgyetang is a traditional soup made of chicken, garlic, rice, scallion, Korean jujube, Korean ginseng, and spices.",
    },
    {
        id: 6,
        title: "Samgyeopsal", 
        category: "Korea",
        price: 16000,
        currency: "₩",
        img: "https://raw.githubusercontent.com/Overated/Asian-Kitchen/main/img/Korea/6-Samgyeopsal.jpg",
        desc: "Consists of grilled slices of pork belly meat that are not marinated or seasoned, served with ssamjang, vegetables, and lettuce leaves to wrap it in.",
    },
    {
        id: 7,
        title: "Gimbap", 
        category: "Korea",
        price: 5000,
        currency: "₩",
        img: "https://raw.githubusercontent.com/Overated/Asian-Kitchen/main/img/Korea/7-Chamchi-gimbap.webp",
        desc: "Cradish, steamed vegetables, ground beef, and rice rolled into a sheet of laver seaweed.",
    },
    // ---------------------------- China Foods ----------------------------
    {
        id: 8,
        title: "Peking Roast Duck", 
        category: "China",
        price: 200,
        currency: "¥",
        img: "",
        desc: "The roast duck can be served with plum sauce or other fruit sauce.",
    },
    {
        id: 9,
        title: "Dan Dan Mian", 
        category: "China",
        price: 20,
        currency: "¥",
        img: "",
        desc: "Dan dan noodle, serving with green onion.",
    },
    {
        id: 10,
        title: "Yangzhou Fried Rice", 
        category: "China",
        price: 80,
        currency: "¥",
        img: "",
        desc: "Hot pepper sauce noodle, serving with soy bean and onion.",
    },
    {
        id: 11,
        title: "Hot Pot", 
        category: "China",
        price: 50,
        currency: "¥",
        img: "",
        desc: "A simmering pot of soup at with various raw ingredients—meat, seafood, vegetables, tofu, and starches.",
    },
    {
        id: 12,
        title: "Wonton Soup", 
        category: "China",
        price: 50,
        currency: "¥",
        img: "",
        desc: "Seasoned chicken broth with filled wontons.",
    },
    // ---------------------------- Japan Foods ----------------------------
    {
        id: 13,
        title: "Chicken Ramen", 
        category: "Japan",
        price: 500,
        currency: "¥",
        img: "",
        desc: "Chicken noodle soup, serving with vegetables such as soy bean, green onion. In an optional you can ask for egg.",
    },
    {
        id: 14,
        title: "Onigiri", 
        category: "Japan",
        price: 200,
        currency: "¥",
        img: "",
        desc: "Rice Sandwich, serving with soy sauce.",
    },
    {
        id: 15,
        title: "Doroyaki", 
        category: "Japan",
        price: 50,
        currency: "¥",
        img: "",
        desc: "Red bean paste dessert, serving with honey.",
    },
    {
        id: 16,
        title: "Sushi", 
        category: "Japan",
        price: 10000,
        currency: "¥",
        img: "",
        desc: ".",
    },
    {
        id: 17,
        title: "Yakitori", 
        category: "Japan",
        price: 150,
        currency: "¥",
        img: "",
        desc: "Bite-sized cuts of chicken grilled on a skewer.",
    },
    {
        id: 18,
        title: "Udon", 
        category: "Japan",
        price: 1250,
        currency: "¥",
        img: "",
        desc: "A thick noodle made from wheat flour.",
    },
    {
        id: 19,
        title: "Miso Soup", 
        category: "Japan",
        price: 900,
        currency: "¥",
        img: "",
        desc: "Soup consisting of a dashi stock into which softened miso paste is mixed.",
    },
    // --------------------------- Thailand Foods ---------------------------
    {
        id: 20,
        title: "Tom Yum Goong", 
        category: "Thailand",
        price: 80,
        currency: "฿",
        img: "",
        desc: "Soup infused with lemongrass, galangal and makrut lime leaves.",
    },
    {
        id: 21,
        title: "Som Tam", 
        category: "Thailand",
        price: 30,
        currency: "฿",
        img: "",
        desc: "A green papaya salad recipe that combines all four tastes - sour, chilli, sweet and salty.",
    },
    {
        id: 22,
        title: "Pad Thai", 
        category: "Thailand",
        price: 50,
        currency: "฿",
        img: "",
        desc: "Stir-fried rice noodles, shrimp or chicken, eggs, groundnuts, lime juice, bean sprouts, tasty tofu cubes, and onions.",
    },
    {
        id: 23,
        title: "Pad Kra Pao Moo", 
        category: "Thailand",
        price: 50,
        currency: "฿",
        img: "",
        desc: "A spicy stir fry of ground pork and Thai basil,erving with Thai style with a crispy fried egg and steamed rice.",
    },
    {
        id: 24,
        title: "Yum Nua", 
        category: "Thailand",
        price: 50,
        currency: "฿",
        img: "",
        desc: "Spicy Thai salad with beef, aromatics, and plenty of herbs and lime juice.",
    },
    // -------------------------- Singapore Foods --------------------------
    {
        id: 25,
        title: "", 
        category: "Singapore",
        price: 500,
        currency: "$",
        img: "",
        desc: "",
    },
];